services:
  - type: web
    name: gerenciador-chamados
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_DEFAULT_EMAIL
        value: admin@local
      - key: ADMIN_DEFAULT_PASSWORD
        value: admin123
